### ISSUE TITLE
Exception: Only the original thread that created a view hierarchy can touch its views

### ISSUE THREAD

**Issue by tranb3r** [FabriBertani/Plugin.Maui.ScreenSecurity#6]
Here is an exception I get sometimes on android:
```
EnableScreenSecurityProtection failed with Exception message: Only the original thread that created a view hierarchy can touch its views.
Exception Stacktrace:    at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
   at Android.Views.Window.SetFlags(WindowManagerFlags , WindowManagerFlags )
   at Plugin.Maui.ScreenSecurity.ScreenSecurityImplementation.EnableScreenSecurityProtection()
  --- End of managed Java.Lang.RuntimeException stack trace ---
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8384)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1476)
	at android.view.View.requestLayout(View.java:24528)
	at android.view.View.setLayoutParams(View.java:17308)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:452)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:103)
	at android.app.Activity.onWindowAttributesChanged(Activity.java:3869)
	at androidx.appcompat.view.WindowCallbackWrapper.onWindowAttributesChanged(WindowCallbackWrapper.java:115)
	at android.view.Window.dispatchWindowAttributesChanged(Window.java:1172)
	at com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged(PhoneWindow.java:3027)
	at android.view.Window.setFlags(Window.java:1148)
```
Could you please take a look?
Thanks

**Comment by tranb3r** [comment]
Also, I've seen the error because I was looking at the logcat while investigating another issue.
Maybe it's not a good idea to catch exceptions in this plugin. Or at least, I think there should be a way for the client to know that something has failed.
What do you think?

**Comment by FabriBertani** [comment]
Hi @tranb3r.

Can you share more details about how you got this exception?

**Comment by tranb3r** [comment]
The error appears in the logs, but I don't know the exact scenario, and I'm not sure I can build a simple repro for it.
I've managed to workaround it by forcing MainThread when calling your plugin.
But I guess if it's mandatory to call `SetFlags` from the UI thread, then it's better to do it in the code of the plugin instead of on the client side.

**Comment by tranb3r** [comment]
Thank you!
